- basepair/__init__.py
- basepair/api.py
https://app.asana.com/0/577079795655810/1175793739400955
- Using temporary credential for any request to AWS services
- Adding pagination for the requests
- Proper API wrappers
- Code styling (pylint)
> HotFix-Updating-Parsing-Response-From-Api-Call-For-List

- basepair/api.py
> HotFix-Avoid-Forcing-Aws-Setting

- basepair/api.py
- bin/basepair
**Task:** https://app.asana.com/0/577079795655810/1183037375235361/f
**TODO:** 
Have to update the error, warning message display after updating the response in analysis API in webapp
> Improvement error handling

- basepair/api.py
**Task:** https://app.asana.com/0/577079795655810/1185245861049265/f
> Feature: Adding genomefiles api

- basepair/api.py
Task: https://app.asana.com/0/1192937991419407/1193887766300793
> HotFix-Adding-Get-Host-By-Domain

- basepair/__init__.py
- basepair/api.py
**Task:** https://app.asana.com/0/577079795655810/1195926337451145/f
Related - https://github.com/basepair/webapp/pull/422
> HotFix-Improvement Error-Msg

- basepair/api.py
- bin/basepair
> Improvement-Basepair-CLI

- basepair/__init__.py
- basepair/infra/webapp/abstract.py
i think this should work, but not completely sure. can you check once before uploading to pypi?
> Hotfix-New-Style-Class

- basepair/__init__.py
- basepair/infra/webapp/abstract.py
- basepair/infra/webapp/analysis.py
**Task:** https://app.asana.com/0/577079795655810/1199208654512733/f
> HotFix-Analysis-Error-Msg

- basepair/api.py
**Task:** https://app.asana.com/0/577079795655810/1199572767652305/f
> HotFix-Wrong-Dict-Name

- basepair/api.py
- bin/basepair
> Add-Validations

- basepair/api.py
- bin/basepair
**Task:** https://app.asana.com/0/577079795655810/1199552716717943/f
> Support-New-Datatype

- basepair/api.py
- basepair/infra/webapp/user.py
- bin/basepair
**Task:** https://app.asana.com/0/577079795655810/1198211199319429/f
> Improvement-Sample-Update

- basepair/api.py
**Task:** https://app.asana.com/0/577079795655810/1199552716717945/f
> BugFix-Sample-Upload

- bin/basepair
**Task:** https://app.asana.com/0/577079795655810/1199123526740799/f
> BugFix-Update-Project

- bin/basepair
**Task:** https://app.asana.com/0/577079795655810/1199655476291920/f
> BugFix-Update-Analysis

- basepair/infra/webapp/abstract.py
Added resource_url endpoint to abstract as it is often needed in other scripts.
> Added resource_url endpoint to abstract as it is often needed in other scripts.

- basepair/__init__.py
- bin/basepair
**Task:** 
https://app.asana.com/0/577079795655810/1199113313740949/f
https://app.asana.com/0/577079795655810/1199694132718790/f
> Improvement-Project-Update

- basepair/infra/webapp/genome_file.py
> Improvement-Update-Genomefiles-Endpoint

- basepair/__init__.py
- basepair/api.py
**Task:** https://app.asana.com/0/577079795655810/1199688337461650/f
> BugFix-AWS-S3-Cmd-Print

- basepair/helpers/nice_print.py
**Task:** https://app.asana.com/0/577079795655810/1199968782129564/f
> Feature-List-Analysis-Files-Full-Path

- basepair/__init__.py
- basepair/helpers/nice_print.py
**task:** https://app.asana.com/0/577079795655810/1199968782129564/f
> Feature-Display-Analysis-File-Path

- basepair/api.py
**Task:** https://app.asana.com/0/577079795655810/1199993317846257/f
> BugFix-Print-Data

- basepair/__init__.py
- basepair/api.py
**Task:** https://app.asana.com/0/577079795655810/1200060309206716/f
> HotFix-Add-Default-Filter-Value

- basepair/__init__.py
- bin/basepair
**Task:** https://app.asana.com/0/577079795655810/1200070364086447/f
> BugFix-Add-Check-For-List-Indivitual-Item

- basepair/__init__.py
- basepair/infra/webapp/sample.py
The extra slash is breaking the request.
> HotFix-Get-Sample-By-Bame-Wrong-Endpoint

- basepair/__init__.py
- basepair/api.py
Task: https://app.asana.com/0/577079795655810/1200380467440748
TODO:
> HotFix-Instance-Dependency-Policy-Generator

- basepair/__init__.py
- basepair/api.py
- basepair/infra/webapp/abstract.py
**Task:** https://app.asana.com/0/577079795655810/1200506664464313/f
> Improvement-Source-Param

- basepair/__init__.py
- basepair/infra/webapp/abstract.py
- basepair/infra/webapp/sample.py
**Task:** https://app.asana.com/0/577079795655810/1200540341326404/f
> HotFix-Dict-Merge

- basepair/__init__.py
- basepair/infra/webapp/abstract.py
This is **urgent** to be able to move forward with the task:
https://app.asana.com/0/1199909113133988/1200642107619665
> Hot fix adding check for response

- basepair/__init__.py
- basepair/infra/webapp/analysis.py
- basepair/infra/webapp/sample.py
> HotFeature-Exposing-WebApp-Libraries

- basepair/__init__.py
- basepair/infra/webapp/abstract.py
- basepair/infra/webapp/analysis.py
- basepair/infra/webapp/upload.py
Tasks: https://app.asana.com/0/1145797231488971/1200279695712826
> Feature-Adding-Upload-Bulk-Import

- basepair/__init__.py
- basepair/api.py
- basepair/infra/webapp/analysis.py
- bin/basepair
**Task** https://app.asana.com/0/1200069044919206/1201028552879615/f
> Feature-Add-Reanalyze-API

- basepair/api.py
- basepair/helpers/nice_print.py
- basepair/infra/webapp/module.py
- bin/basepair
This PR adds a certain feature in List Modules and Pipeline Flow
list pipeline_modules -u 10
list pipeline_modules --uid 10
it will show all the modules for pipeline id 10
list module -u 447
this will give detail of a module
Dependency on PR -
basepair/webapp#1126
Related Ticket --
https://app.asana.com/0/1201368373933132/1201406835914429
> Feature-detail of module and list modules of workflow

- basepair/api.py
- bin/basepair
User should be able to create and update Module or Pipeline via -f or —file
Example -
create module —file1 test.yaml or test.yml
create moudle -f test.yaml or test.yml
Related Ticket -
https://app.asana.com/0/1201368373933132/1201589980257997
> Improvement:added -f --file argument for .yaml .yml

- .gitignore
Secured configuration files in .gitignore for local
> Secure: Added config files in gitignore

- basepair/__init__.py
- basepair/api.py
Bug: https://basepairtech.atlassian.net/browse/WEB-861
> BugFix: Pass proper arguments to the Upload.list() method

- basepair/__init__.py
> Upgrade the version to 2.1.0

- basepair/__init__.py
- basepair/api.py
- bin/common_parser.py
- bin/datatypes/pipeline.py
JIRA: https://basepairtech.atlassian.net/browse/WEBAPP-469
> Added pipeline sharing permissions

- basepair/modules/aws/s3.py
- basepair/modules/storage/drivers/abstract.py
- basepair/modules/storage/drivers/aws_s3.py
This PR adds functionality to list buckets from aws.
> List buckets

- basepair/__init__.py
- basepair/modules/analysis_log/__init__.py
- basepair/modules/analysis_log/abstract.py
- basepair/modules/analysis_log/analysis.py
- basepair/modules/analysis_log/infra.py
- basepair/modules/aws/hos.py
- basepair/modules/ssftp/__init__.py
- basepair/modules/ssftp/drivers/__init__.py
- basepair/modules/ssftp/drivers/ftp.py
- basepair/modules/ssftp/drivers/psv_ftp.py
- basepair/modules/ssftp/drivers/sftp.py
- basepair/modules/ssftp/ssftp.py
- basepair/modules/storage/drivers/abstract.py
- basepair/modules/storage/drivers/aws_s3.py
- basepair/modules/storage/main.py
- setup.py
To unify the source code for the storage wrapper.
We just added the missed methods so we can point to this wrapper from the bioinfo repo instead of loading a replication of the same.
Require:
https://github.com/basepair/bioinfo/pull/298
> Refactor-Step-03-Moving-Utils-To-Worker

- basepair/modules/aws/policy.py
This PR allows to add sts assume role policy.
> Adding method to add policy for assume role

- .github/workflows/publish-test-package.yml
- setup.py
Create a github action to create test package for the `basepair-python` package to be used by the stage (testing) webapp environement.
> Test package workflow

- app/basepair/modules/aws/s3.py
Presigned URL generation improvement
- I am extending the method for presgined url generation. now you can generate the presigned url for post and put permission also. the method no longer restricts to get permission
> Extend presigned url method for post permission
